os: windows
language: python
python:
- "3.7"
sudo: false
cache: pip3
install:
- pip3 install -r requirements.txt
- pip3 install coverage
- pip3 install coveralls
#commands to run the tests
script:
- pytest --cov=api
- coverage report
- coveralls
after success:
- coveralls


